### PR TITLE
Update the asmtest

### PR DESCRIPTION
**Pull request by rogerchang23424**
There are two update in the PR

1. Replace the bitmanip asmtest with upstream one 
    issue: https://github.com/gem5/gem5/issues/883
3. Correct the m5 operation for RV32
    issue: https://github.com/gem5/gem5/issues/881
    fix PR: https://github.com/gem5/gem5/pull/900

### CODE REVIEW

**Comment by powerjg** [comment]
Generally, this looks good to me. Can you explain the dependences between different PRs? Are each of these changes independent or do we need to merge and update resources before we can merge the gem5 fixes?

**Comment by rogerchang23424** [comment]
The PR combine the three types of resource update

1. Replace the bitmanip test cases with opstream one
   - [Revert "resources: Add RV32/RV64 bitmanip 1.0 instruction tests"](https://github.com/gem5/gem5-resources/pull/25/commits/a3b5f1911daa39c92c15f8b8660cb7bf087a19c5) 
   - [Remove Bit-manipulation ISA tests](https://github.com/gem5/gem5-resources/pull/25/commits/94b88325ecb4eb7b56b32bd1b0cd63db04e2e1bf) 
   - [Update asmtest](https://github.com/gem5/gem5-resources/pull/25/commits/7ca891699a4516a26abaaf6e58c86c9fe86c190d)
   note: the PR https://github.com/gem5/gem5/pull/931 required to update this resource to make it pass test.
2. Fix the RV32 m5op calls
   - [Fix the m5 operation for RV32](https://github.com/gem5/gem5-resources/pull/25/commits/3114c821e71c7d41be0f92b84262c370bcf4e43e)
   - [Update the macro/mt syscal implementation](https://github.com/gem5/gem5-resources/pull/25/commits/3f680f52ead658915da296c9302d07090af1a0b9)
3. Fix the cbo.zero tests
   -  [Fix the cbo.zero test failed issue](https://github.com/gem5/gem5-resources/pull/25/commits/508c33f13cfdf2f66851a13f0c22e35088e91b3a)

I'm not familiar with the version control of gem5 resources. I hope that we can apply the fixs by upgrade one version.

@powerjg and @Harshil2107 how do you think?

**Comment by Harshil2107** [comment]
I can rebuild the binaries and add them as a new version to the asmtest binaries that we have and that should be all the changes we need.

**Comment by Harshil2107** [comment]
I was running into some errors while compiling the binaries, which were mostly due to missing depencencies, even after building the cross compiler. I have fixed most of them. I will update the binaries and update the readme in a seperate PR.

**Comment by Harshil2107** [comment]
I have updated and pushed all the binaries to the Mongodb database. They should be accessible with the same id but a higher version that is "2.0.0". Let me know if I need to do anything else.

**Comment by rogerchang23424** [comment]
Thanks @Harshil2107 for updating binary.

**Comment by rogerchang23424** [comment]
> I was running into some errors while compiling the binaries, which were mostly due to missing depencencies, even after building the cross compiler. I have fixed most of them. I will update the binaries and update the readme in a seperate PR.

Do you update the binary with the fixed patch?

**Comment by Harshil2107** [comment]
> Do you update the binary with the fixed patch?

I think so, I used the develop branch which has PR 900 (https://github.com/gem5/gem5/pull/900) merged.

The issues where with makefile overriding variables, I will push a PR fixing it.

**Review by Harshil2107 — APPROVED** [review]
lgtm

**Pull request merged**
