### PR TITLE
Reorganize the resources repository

### PR DESCRIPTION
**Pull request by Harshil2107**
This moves and creates the following directories
  - [x] add riscv-fs-alt folder
    - [x] rename riscv-fs to riscv-busy box
    - [x] delete opensbi-alt
    - [x] riscv boot no disk
    - [x] rename riscv-ubuntu to sicv ubuntu 20.04
    - [x] readme telling what each directory is
  - [x] add riscv-fs folder
    - [x]  riscv-ubutuntu 22.04 to riscv-ubuntu
    - [x] open-sbi
    - [x] readme telling what each directory is
- [x] add a examples folder, and move the following directories
  - [x] asm tests
  - [x] matrix multiply
  - [x] getting started
  - [x] print this
  - [x] insttests
  - [x] simple ( figure out what simple is first)
- [x] add deprecated folder
  - [x] hack back
  - [x] parsec
    
edits:

- move matrix-multiply-omp to exampls
- move simple to deprecated

### CODE REVIEW

**Comment by Harshil2107** [comment]
It looks like simple contains code to make some general resources like binaries that just run m5 exit, like https://resources.gem5.org/resources/x86-m5-exit?version=1.0.0 or https://resources.gem5.org/resources/x86-m5-exit-repeat?version=1.0.0, but not all files in the directory have a corresponding resource. where should I move this directory in examples?

**Review by erin-le — COMMENTED** [review]
Aside from potentially renaming riscv-fs and riscv-fs-alt to something else to make the difference more immediately apparent (maybe riscv-fs-current and riscv-fs-old), looks good.

**Review by erin-le — APPROVED** [review]

**Comment by powerjg** [comment]
Should this be squashed? The commits are not labeled well.

**Comment by Harshil2107** [comment]
yes, they should be squashed

**Pull request merged**
