### PR TITLE
resources: Remove out of date GPUFS README

### PR DESCRIPTION
**Pull request by abmerop**

### CODE REVIEW

**Review by mattsinc — COMMENTED** [review]
Remind me what the alternative is going to be now?

**Review by ivanaamit — APPROVED** [review]

**Comment by mattsinc** [comment]
@ivanaamit : I wish you would not have approved this and merged it, as there was a pending, unanswered question.  As is, I believe merging this means there are effectively no instructions for how to use gem5's GPUFS mode since this patch removed the README.  I was waiting on @abmerop to let me know what the alternative directions were going to be.

**Comment by powerjg** [comment]
Sorry, @mattsinc, this was my call. Do you want us to revert?

**Comment by mattsinc** [comment]
> Sorry, @mattsinc, this was my call. Do you want us to revert?

Let's just let it be, and @abmerop and I will work to update whatever documentation is/isn't missing next week.  Sorry for being overly aggressive here, @ivanaamit , I know you were just trying to help.

**Pull request merged**
